export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const INCREMENT_ITEM_CART = "INCREMENT_ITEM_CART";
export const DECREMENT_ITEM_CART = "DECREMENT_ITEM_CART";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const LOGIN_FETCHING = "LOGIN_FETCHING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const GET_USER_START = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const ADD_USER_FETCHING = "ADD_USER_FETCHING";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const EDIT_PRODUCT_START = "EDIT_PRODUCT_START";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

// Category

export const GET_CATE_START = "GET_CATE_START";
export const GET_CATE_SUCCESS = "GET_CATE_SUCCESS";
export const GET_CATE_ERROR = "GET_CATE_ERROR";

export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const GET_PRODUCT_BY_CATEGORY_START = "GET_PRODUCT_BY_CATEGORY_START";
